### ISSUE TITLE
Feature: add `showOtherItem` and `showNoneItem` support to `Dropdown`

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#52] opened 2023-04-18 21:25 UTC
Per SurveyJS documentation, survey builders should be able to specify a `Dropdown` as [`showOtherItem`](https://surveyjs.io/form-library/documentation/api-reference/dropdown-menu-model#showOtherItem) and/or [`showNoneItem`](https://surveyjs.io/form-library/documentation/api-reference/dropdown-menu-model#showNoneItem).

In the case of `showOtherItem`, a `ReactiveTextField` should appear and set the value for this element if `other` is selected from the `Dropdown`.

<img width="686" alt="Screen Shot 2023-04-18 at 4 24 40 PM" src="https://user-images.githubusercontent.com/27712906/232908563-0eff31aa-d8e5-4553-9865-6b4113584501.png">
<img width="708" alt="Screen Shot 2023-04-18 at 4 24 50 PM" src="https://user-images.githubusercontent.com/27712906/232908590-2b11a598-a04a-4875-b703-76675919e125.png">

**Comment by laogao** [comment] 2023-05-04 05:59
@ChopinDavid Greetings! Have you noticed there might be a minor difference in behavior between the current implementation and the "official" one by SurveyJS, namely, the `name` key used in answers? In this case, we "re-used" the `name` of the element to store the "other" value. However, SurveyJS would set the original `name` field's value as "other" and use something like `${name}-Comment` for the actual "other" value.

**Comment by goxiaoy** [comment] 2023-05-10 04:50
>  SurveyJS would set the original name field's value as "other" and use something like ${name}-Comment for the actual "other" value.

We should align this behavior with SurveyJS js version even if I don't like this kind of solution.
Keep this issue open until fixed it

**Comment by ChopinDavid** [comment] 2023-05-10 12:47
I've been pretty involved with #30 and almost have something working there, but should be turning my attention to this issue in the coming weeks.

**Comment by goxiaoy** [comment] 2023-06-01 10:43
duplicate of #71

**Closed by goxiaoy** 2023-06-01 10:43 UTC
